#!@bash@/bin/bash

bluetoothactive="$(@bluez-tools@/bin/bt-adapter --info | grep Powered | sed 's|.*Powered: \(.\) .*|\1|')"

if [[ "$BLOCK_BUTTON" -eq 2 ]] ; then # Middle-click
    if [[ "$(@procps@/bin/pgrep blueman-applet)" == "" ]] ; then # Start blueman-applet if it's not running already
	    @i3@/bin/i3-msg exec -- --no-startup-id "@blueman@/bin/blueman-applet" >/dev/null
    else
        @procps@/bin/pkill blueman-applet >/dev/null
    fi
elif [[ "$BLOCK_BUTTON" -eq 3 ]] ; then # Right-click
    if [[ "$bluetoothactive" -eq 0 ]] ; then
        @bluez-tools@/bin/bt-adapter --set Powered 1
    else
        @bluez-tools@/bin/bt-adapter --set Powered 0
    fi
fi

echo "BT $bluetoothactive"
echo "BT $bluetoothactive"
if [[ "$bluetoothactive" -eq 1 ]] ; then
    if [[ bluetooth-connected ]] ; then
        echo \#00FF00
    else
        echo \#FFA500
    fi
else
    echo \#FF0000
fi
